service: battlesnake

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-west-2
  memorySize: 1024

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app/main.application
    packRequirements: false
  pythonRequirements:


functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
